language: cpp

compiler:
  - clang
  - gcc
os:
  - osx
  - linux
matrix:
  exclude:
    - os: linux
      compiler: clang
rvm:
  - 2.2
  
before_install:
  # update packages
  - cmake --version
  - gem install msgpack
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt update -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt upgrade -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -y build-essential libmsgpack-dev cmake libtool ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install msgpack ; fi
     
before_script:  
  - cmake .

script:
  - make
  # - ./bin/fluent-test
